apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id | dump }}
  {%- if values.description %}
  description: ${{ values.description | dump }}
  {%- endif %}
  annotations:
    gitlab.com/project-slug: ${{ values.owner }}/${{ values.name }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{ values.name }}
    janus-idp.io/tekton: ${{ values.name }}
    argocd/app-name: ${{ values.name }}
  links:
    - url: https://workspaces.openshift.com/#https://${{ values.repo_url }}
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
