apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id | dump }}
  {%- if values.description %}
  description: ${{ values.description | dump }}
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://workspaces.openshift.com/#https://${{ values.repoUrl }}
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
