---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
    ${{ values.description }}
  tags:
    - rhdh-exercises
    - sample
  links:
    - title: Red Hat Developer Hub Website
      url: https://developers.redhat.com/rhdh/overview
    - title: Red Hat Developer Hub Documentation
      url: https://access.redhat.com/documentation/en-us/red_hat_developer_hub/
  annotations:
    gitlab.com/project-slug: ${{ values.owner }}/${{ values.repoName }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: ${{ values.owner }}
  lifecycle: experimental
  system: sample-system
  providesApis:
    - ${{ values.name }}
