site_name: ${{ values.name }}
site_description: ${{ values.description }}
repo_url: https://${{ values.repoUrl }}
edit_uri: edit/main/docs

# Note for content editors, edit only the section below
nav:
  - Home: index.md

plugins:
  - techdocs-core
