---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sample-software-template
  title: Sample Software Template from Backstage
  description: Sample scaffolder template for demo purposes
  tags:
    - sample
    - gitlab
    - rhdh-exercises
    - workshop
  annotations:
    backstage.io/template-version: 'v1.1.0'
spec:
  owner: group:rhdh
  type: service
  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Provide information about the new component
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:help: Provide an unique name to identify the component
          maxLength: 50
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
          ui:help: Short description of this new component
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:help: Who is the owner of this new component?
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          description: Base url of the GitLab server (not include protocol such as https:// or ssh://)
          ui:help: Base url of the GitLab server (not include protocol such as https:// or ssh://)
          #ui:field: RepoUrlPicker
          #ui:options:
          #  rows: 5

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetch-base
      name: Fetching and generating the source code
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner | parseEntityRef | pick('name') }}
          repoUrl: ${{ parameters.repoUrl }}?owner=${{ parameters.owner | parseEntityRef | pick('name') }}&repo=${{ parameters.name }}

    - id: create-provenance-annotation
      name: Append the entityRef of this template to the entityRef
      action: catalog:scaffolded-from

    - id: publish
      name: Publishing to the GitLab Repository
      action: publish:gitlab
      input:
        #allowedHosts: ['gitlab.com']
        repoUrl: ${{ parameters.repoUrl }}?owner=${{ parameters.owner | parseEntityRef | pick('name')  }}&repo=${{ parameters.name }}
        repoVisibility: public
        defaultBranch: main

    #- id: create-version-annotation
    #  name: Create Template Version Annotation
    #  action: catalog:template:version
    #  input:
    #    templateVersion: ${{ parameters.version }}        

    - id: register
      name: Registering the Catalog Info
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  # some outputs which are saved along with the job for use in the frontend
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
