apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: angular-template-gitlab
  title: Angular Template for GitLab
  description: Create a new Angular website project
  tags:
    - recommended
    - angular
    - gitlab
    - rhdh-exercises
  annotations:
    backstage.io/template-version: 'v1.0.0'
spec:
  owner: group:rhdh
  type: website
  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          maxLength: 50
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
          ui:help: Provide an unique name to identify the component
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Help others understand what this website is for
          ui:help: Short description of this new website
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
        - namespace
      properties:
        repoUrl:
          title: Repository Location
          type: string
          description: Base url of the GitLab server (not include protocol such as https:// or ssh://)
          ui:help: Base url of the GitLab server (not include protocol such as https:// or ssh://)
          default: 'gitlab.com'
          #ui:field: RepoUrlPicker
          #ui:options:
          #  allowedHosts:
          #    - github.com
        argocdInstance:
          title: ArgoCD Instance
          type: string
          description: ArgoCD instance to declare the Application
          ui:help: ArgoCD instance to declare the Application
          default: 'openshift-gitops'

  # here's the steps that are executed in series in the scaffolded backend
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.component_id }}
          component_id: ${{ parameters.component_id }}
          description:  ${{ parameters.description }}
          repo_url: ${{ parameters.repoUrl }}?owner=${{ parameters.owner | parseEntityRef | pick('name') }}&repo=${{ parameters.component_id }}
          git_repo_url: "https://${{ parameters.repoUrl }}/${{ parameters.owner | parseEntityRef | pick('name') }}/${{ parameters.component_id }}.git"
          owner: ${{ parameters.owner | parseEntityRef | pick('name') }}

    - id: create-provenance-annotation
      name: Append the entityRef of this template to the entityRef
      action: catalog:scaffolded-from

    - id: publish
      name: Publishing to the GitLab Repository
      action: publish:gitlab
      input:
        #allowedHosts: ['gitlab.com']
        repoUrl: ${{ parameters.repoUrl }}?owner=${{ parameters.owner | parseEntityRef | pick('name') }}&repo=${{ parameters.component_id }}
        repoVisibility: public
        defaultBranch: main

    - id: register
      name: Register Entity in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: create-argocd-resources
      name: Create the ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ parameters.component_id }}
        argoInstance: ${{ parameters.argocdInstance }} 
        namespace: ${{ parameters.argocdInstance }}
        repoUrl: ${{ steps.publish.output.remoteUrl }}
        path: argocd
        
  # some outputs which are saved along with the job for use in the frontend
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
