---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ${{ values.name }}-pipeline-eventlistener  
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: gitlab-listener-trigger