---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: gitlab-listener-trigger
spec:
  interceptors:
    - ref:
        name: gitlab
      params:
        - name: secretRef
          value:
            secretName: gitlab-webhook
            secretKey: secret
        - name: eventTypes
          value: ["push"]
    - ref:
        name: cel
      params:
        - name: "filter"
          value: body.ref == 'refs/heads/main'
  bindings:
    - ref: ${{ values.name }}-pipeline-triggerbinding
  template:
    ref: ${{ values.name }}-pipeline-triggertemplate