---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ${{ values.name }}-pipeline-triggertemplate
spec:
  params:
    - name: git_url
      description: The git repository that hosts context
    - name: git_revision
      description: The revision of the repository
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: ${{ values.name }}-pipeline-run-
        annotations:
          tekton.dev/gitURL: "$(tt.params.git_url)"
      spec:
        pipelineRef:
          name: ${{ values.name }}-pipeline
        params:
          - name: APP_NAME
            value: ${{ values.name }}
          - name: GIT_REPO
            value: $(tt.params.git_url)
          - name: GIT_REVISION
            value: $(tt.params.git_revision)
          - name: IMAGE_NAME
            value: 'image-registry.openshift-image-registry.svc:5000/${{ values.name }}/${{ values.name }}'
          - name: PATH_CONTEXT
            value: .
        workspaces:
          - name: workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                volumeMode: Filesystem